[book]
authors = ["Vladimir Timofeenko","Jake Berkowsky","Mike Mitrowski","Ryan O'Connell"]
language = "en"
multilingual = false
src = "src"
title = "Sentry documentation"

[output.html]
git-repository-url = "https://github.com/Snowflake-Labs/Sentry"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/Snowflake-Labs/Sentry/edit/main/docs/src"
additional-css = ["custom.css"]

[preprocessor.runConvertedFileIncludes]
command = "mdsh --inputs ./src/guide/installation/streamlit-in-snowflake.md"

[preprocessor.mkSprocDocs]
command = "mdsh --inputs ./src/reference/queries.md"

[preprocessor.renderControlMapping]
command = "mdsh --inputs ./src/reference/control-mapping.md"

[preprocessor.updateReadme]
command = "mdsh --inputs ./src/guide/installation/README.md"
