name: "Tear down and create the application"
on:
  workflow_dispatch: # Run only manually

jobs:
  tear-down-and-deploy-native-app:
    runs-on: ubuntu-latest

    steps:
      # HACF if environment is not set

      # Boilerplate
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      # Actual deployment action
      - name: "Tear down and create the application"
        # Effectively runs a wrapper around a tiny build script + snowcli to deploy the application
        # For the wrapper source, see flake.nix
        run: nix run .#tear-down-and-deploy-native-app-in-own-account
        env:
          # This repo uses a custom wrapper around Snowflake CLI
          # For alternative GH action config, see
          # https://github.com/snowflakedb/snowflake-cli/issues/872
          #
          # NOTE: database and schema are not needed, applications are account level objects
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          NA_GRANT_TO_ROLE: ACCOUNTADMIN
